apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pull-request
  title: Integrar projeto ao CI/CD
  description: Adicione um projeto existente a esteira CI/CD
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Preencha as informações
      required:
        - name
        - description
        - type
      properties:
        component_id:
          title: Nome
          type: string
          description: Nome único do componente
          ui:field: EntityNamePicker
          ui:autofocus: true
        description:
          title: Descrição
          type: string
          description: Descrição do componente
        type:
          title: Tipo
          type: string
          enum: ["service", "website", "library"]
          description: Tipo do componente
        owner:
          title: Dono
          type: string
          description: Dono do componente
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Escolha uma localização
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Gerando arquivos
      action: fetch:template
      input:
        url: ./template
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}

    - id: webhook
      name: Adicionando Webhook
      action: 'github:webhook'
      input:
        repoUrl: ${{ parameters.repoUrl }}
        webhookUrl: https://jenkins.consigmais.com.br/generic-webhook-trigger/invoke?token=consigmais_webhook
        contentType: 'json'

    - id: publish
      name: Publicando PR
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: "Preparando para a esteira CI/CD: ${{parameters.name}}"
        branchName: deployment
        description: |
          # Preparando para a esteira CI/CD: ${{parameters.name}}

          ${{ parameters.description if parameters.description }}

    - id: register
      name: Registrando no catalogo
      action: 'catalog:register'
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/template.yaml"


  output:
    links:
      - url: ${{steps.publish.output.remoteUrl}}
        text: "Go to PR"
