apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pull-request
  title: Pull Request Action template
  description: scaffolder v1beta3 template demo publishing to PR on existing git repository
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Preencha as informações
      required:
        - name
      properties:
        name:
          title: Nome
          type: string
          description: Nome único do componente
          ui:field: EntityNamePicker
          ui:autofocus: true
        description:
          title: Descrição
          type: string
          description: Descrição do componente
        type:
          title: Tipo
          type: string
          enum: ["service", "website", "library"]
          description: Tipo do componente
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Gerando arquivos
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{parameters.name}}

    - id: webhook
      name: Adicionando Webhook
      action: 'github:webhook'
      input:
        repoUrl: ${{ parameters.repoUrl }}
        webhookUrl: https://jenkins.consigmais.com.br/generic-webhook-trigger/invoke?token=consigmais_webhook
        contentType: 'json'

    - id: publish
      name: Publicando PR
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: "Preparando para a esteira CI/CD: ${{parameters.name}}"
        branchName: deployment
        description: |
          # Preparando para a esteira CI/CD: ${{parameters.name}}

          ${{ parameters.description if parameters.description }}

  output:
    links:
      - url: ${{steps.publish.output.remoteUrl}}
        text: "Go to PR"
